src/javascript/app/App.jsx, src/javascript/app/SearchView/SearchView.jsx
https://jira.jahia.org/browse/BACKLOG-12948
Implemented categories facet
=> Added categories facet to augmented search ui

package.json, pom.xml, yarn.lock
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-12286: Update pom.xml file for V8 compatibility

pom.xml
https://jira.jahia.org/browse/BACKLOG-12729
Update version and signature
=> BACKLOG-12729 Update version and signature

pom.xml
https://jira.jahia.org/browse/BACKLOG-13746
Update version and signature
=> BACKLOG-13746 Update version and signature

.circleci/.circleci.settings.xml, .circleci/config.yml
=> BACKLOG-13739 - Added build and publish on Circleci

README.md, pom.xml
And updated the project's readme with badges
=> Restored previous version of the pom file

.circleci/.circleci.settings.xml, pom.xml
https://jira.jahia.org/browse/BACKLOG-14308
=> Backlog 14308

README.md, package.json, src/javascript/app/App.jsx, src/javascript/app/SearchView/SearchView.jsx, yarn.lock
https://jira.jahia.org/browse/BACKLOG-14077
https://jira.jahia.org/browse/BACKLOG-14141
Upgraded Elastic ui to 1.4.1 and provided example of conditional facets support, fixed sorting by title and updated README
=> Backlog 14077 backlog 14141 upgrade elastic ui and conditional facets support

yarn.lock
Upgrade dependencies for security purposes
=> BACKLOG-14518: Fix dependencies

src/javascript/app/App.jsx, src/javascript/app/SearchView/SearchView.jsx
https://jira.jahia.org/browse/BACKLOG-12599
Implemented search on initial load
=> BACKLOG-12599 added empty search on initial load and empty search facets

package.json, src/javascript/app/App.jsx, src/javascript/app/SearchView/SearchView.jsx, src/javascript/app/SearchView/TreeFacet/Tree/Tree.jsx, src/javascript/app/SearchView/TreeFacet/Tree/TreeNode/TreeNode.jsx, src/javascript/app/SearchView/TreeFacet/TreeFacet.jsx, yarn.lock
https://jira.jahia.org/browse/BACKLOG-14140
Implemented ui for hierarchical facets
=> Backlog 14140 integrate tree facet in ui

package.json, src/javascript/app/App.jsx, yarn.lock
https://jira.jahia.org/browse/PROJECT-XXX
Remove node type filter
=> BACKLOG-14079 Remove nodetype filter

package.json, yarn.lock
https://jira.jahia.org/browse/QA-13197
Connector version bump
=> QA-13197 added reference for new version of connector

package.json, src/javascript/app/App.jsx, src/javascript/app/SearchView/SearchView.jsx, src/javascript/app/SearchView/TreeFacet/Tree/Tree.jsx, src/javascript/app/SearchView/TreeFacet/Tree/TreeNode/TreeNode.jsx, src/javascript/app/SearchView/TreeFacet/TreeFacet.jsx
https://jira.jahia.org/browse/BACKLOG-14868
Implemented filtering for tree facets, tested on larger data set
=> BACKLOG-14868 implement filtering for tree facets, tested on larger data set

package.json, pom.xml, src/javascript/app/SearchView/TreeFacet/Tree/Tree.jsx, src/javascript/app/SearchView/TreeFacet/Tree/TreeNode/TreeNode.jsx
https://jira.jahia.org/browse/PROJECT-XXX
=> Prepare release 3.0.0

package.json, pom.xml, src/javascript/app/SearchView/TreeFacet/Tree/Tree.jsx, yarn.lock
https://jira.jahia.org/browse/PROJECT-XXX
=> Keep tree open while selecting facets, refreshing page will lose state

package.json, src/javascript/app/SearchView/SearchView.jsx, yarn.lock
https://support.jahia.com/browse/PRODUCT-51
I updated the searchView in order to keep track of the searchTerm to have information sent to jExperience and see the statistics about search.
Note : I defined a minimal number of character to start tracking (3) and I sent search term only 3s after the last keyup in order to have the complete searchTerm.
=> update searchView to track searchTerm and send event to jExp

package.json, yarn.lock
https://jira.jahia.org/browse/BACKLOG-17078
=> BACKLOG-17078 - Update connector version

pom.xml
https://jira.jahia.org/browse/TECH-1055
=> TECH-1055: Fixed compilation, add dependency

package.json, pom.xml, src/javascript/app/SearchView/SearchView.jsx, src/javascript/app/SearchView/TreeFacet/Tree/Tree.jsx, yarn.lock
https://jira.jahia.org/browse/TECH-1252
=> TECH-1252: Add sync-pom configuration

.github/workflows/on-merge.yml, .github/workflows/on-release.yml, package.json, pom.xml, webpack.config.js, yarn.lock
https://jira.jahia.org/browse/TECH-1271
Add cyclonedx-maven-plugin and create/upload SBOMs on merge and release
=> TECH-1271: Add SBOM creation
